-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 23:09:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Bobrikova_Filatov_data_mining_python
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bobrikova_Filatov_data_mining_python
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bobrikova_Filatov_data_mining_python` DEFAULT CHARACTER SET utf8 ;
USE `Bobrikova_Filatov_data_mining_python` ;

-- -----------------------------------------------------
-- Table `Bobrikova_Filatov_data_mining_python`.`home_town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bobrikova_Filatov_data_mining_python`.`home_town` (
  `vk_id` INT NOT NULL,
  `home_town` VARCHAR(45) NULL,
  PRIMARY KEY (`vk_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
